[Uboreshaji Modeli] Limit transformers version
Before this patch, running
`pip install -r Uboreshaji_Modeli/requirements.txt` could install the
transformers library with major version 5, which has a breaking change
that causes `python3 -m Uboreshaji_Modeli.main` to raise the following
exception:

```
ValueError: At least one stride in the given numpy array is negative,
and tensors with negative strides are not currently supported. (You can
probably work around this by making a copy of your array  with
array.copy().)
```

This patch limits the transformers library to be older than 5.0.0.

PiperOrigin-RevId: 889787355